import { CategoryCode, DietaryLabelCode, MealTime, MenuSource } from "../common/enums";

type CafeteriaSeed = {
  key: string;
  name: string;
  description: string;
  location: {
    building: string;
    floor: string;
    address?: string;
    lat?: number;
    lng?: number;
  };
  openingHours: Record<string, Array<{ open: string; close: string }>>;
};

type MenuItemSeed = {
  key: string;
  cafeteriaKey: string;
  source: MenuSource;
  name: string;
  description: string;
  category: CategoryCode;
  price: number;
  mealTime: MealTime;
  ingredients: string[];
  allergens: string[];
  dietaryLabels: DietaryLabelCode[];
};

export type DailyMenuSourceSeed = {
  cafeteriaKey: string;
  dvsCd: string;
  menuNamePrefix: string;
};

const weekdayHours = (ranges: Array<{ open: string; close: string }>) => ({
  monday: ranges,
  tuesday: ranges,
  wednesday: ranges,
  thursday: ranges,
  friday: ranges,
});

const weekdayBreakfastLunchDinner = {
  monday: [
    { open: "08:00", close: "09:00" },
    { open: "11:20", close: "13:30" },
    { open: "17:20", close: "19:00" },
  ],
  tuesday: [
    { open: "08:00", close: "09:00" },
    { open: "11:20", close: "13:30" },
    { open: "17:20", close: "19:00" },
  ],
  wednesday: [
    { open: "08:00", close: "09:00" },
    { open: "11:20", close: "13:30" },
    { open: "17:20", close: "19:00" },
  ],
  thursday: [
    { open: "08:00", close: "09:00" },
    { open: "11:20", close: "13:30" },
    { open: "17:20", close: "19:00" },
  ],
  friday: [
    { open: "08:00", close: "09:00" },
    { open: "11:20", close: "13:30" },
    { open: "17:20", close: "19:00" },
  ],
};

const westBreakfastLunchDinner = weekdayHours([
  { open: "08:00", close: "09:30" },
  { open: "11:30", close: "13:30" },
  { open: "17:00", close: "19:00" },
]);

const eastStudentBreakfastLunchDinner = weekdayHours([
  { open: "08:00", close: "10:00" },
  { open: "11:30", close: "14:00" },
  { open: "17:30", close: "19:00" },
]);

const eastFacultyLunchDinner = weekdayHours([
  { open: "11:30", close: "13:30" },
  { open: "17:30", close: "19:00" },
]);

const facultyHallLunchDinner = weekdayHours([
  { open: "11:20", close: "13:30" },
  { open: "17:30", close: "18:30" },
]);

const munjiBreakfastLunchDinner = weekdayHours([
  { open: "07:30", close: "09:00" },
  { open: "11:00", close: "13:00" },
  { open: "17:00", close: "18:40" },
]);

const hwaamBreakfastLunchDinner = weekdayHours([
  { open: "07:30", close: "09:00" },
  { open: "11:30", close: "13:00" },
  { open: "17:30", close: "18:40" },
]);

const kaimaruFoodCourtHours = {
  monday: [{ open: "10:30", close: "20:00" }],
  tuesday: [{ open: "10:30", close: "20:00" }],
  wednesday: [{ open: "10:30", close: "20:00" }],
  thursday: [{ open: "10:30", close: "20:00" }],
  friday: [{ open: "10:30", close: "20:00" }],
};

const juiceKingHours = {
  monday: [{ open: "09:30", close: "20:00" }],
  tuesday: [{ open: "09:30", close: "20:00" }],
  wednesday: [{ open: "09:30", close: "20:00" }],
  thursday: [{ open: "09:30", close: "20:00" }],
  friday: [{ open: "09:30", close: "20:00" }],
};

const weekdayTenThirtyToEight = weekdayHours([{ open: "10:30", close: "20:00" }]);
const weekdayTenToSeven = weekdayHours([{ open: "10:00", close: "19:00" }]);

const kaimaruN11Location = {
  building: "N11",
  floor: "1F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.37379,
  lng: 127.35925,
};

const pulbitmaruN12Location = {
  building: "N12",
  floor: "1F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.374,
  lng: 127.3597,
};

const westStudentCenterW2Location = {
  building: "W2",
  floor: "1F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.36734,
  lng: 127.36097,
};

const eastFacultyClubE5Location = {
  building: "E5",
  floor: "1F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.36926,
  lng: 127.3636,
};

const facultyClubN6Location = {
  building: "N6",
  floor: "1-2F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.37474,
  lng: 127.36474,
};

const munjiCampusLocation = {
  building: "Munji Campus",
  floor: "1F",
  address: "193 Munji-ro, Yuseong-gu, Daejeon",
  lat: 36.39274,
  lng: 127.39912,
};

const hwaamDormitoryLocation = {
  building: "Hwaam Dormitory",
  floor: "1F",
  lat: 36.40803,
  lng: 127.38144,
};

const seoulCampusLocation = {
  building: "Seoul Campus",
  floor: "1F",
  address: "85 Hoegi-ro, Dongdaemun-gu, Seoul",
  lat: 37.5918,
  lng: 127.04613,
};

const chungMoonSoulE16Location = {
  building: "E16",
  floor: "1F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.37154,
  lng: 127.36191,
};

const taeulGwanN13Location = {
  building: "N13",
  floor: "2F",
  address: "291 Daehak-ro, Yuseong-gu, Daejeon",
  lat: 36.3732,
  lng: 127.36004,
};

export const KAIST_CAFETERIA_SEEDS: CafeteriaSeed[] = [
  {
    key: "kaimaru-north-cafeteria",
    name: "카이마루(북측 카페테리아)",
    description: "KAIST 학생식당(N11) 1층 북측 카페테리아.",
    location: kaimaruN11Location,
    openingHours: weekdayBreakfastLunchDinner,
  },
  {
    key: "west-cafeteria",
    name: "서맛골(서측식당)",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 서측식당.",
    location: westStudentCenterW2Location,
    openingHours: westBreakfastLunchDinner,
  },
  {
    key: "east-student-cafeteria",
    name: "동맛골(동측 학생식당)",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 동측 학생식당.",
    location: eastFacultyClubE5Location,
    openingHours: eastStudentBreakfastLunchDinner,
  },
  {
    key: "east-faculty-cafeteria",
    name: "동맛골(동측 교직원식당)",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 동측 교직원식당.",
    location: { ...eastFacultyClubE5Location, floor: "2F" },
    openingHours: eastFacultyLunchDinner,
  },
  {
    key: "faculty-hall-cafeteria",
    name: "교수회관",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 교수회관 식당.",
    location: facultyClubN6Location,
    openingHours: facultyHallLunchDinner,
  },
  {
    key: "munji-cafeteria",
    name: "문지캠퍼스 구내식당",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 문지캠퍼스 구내식당.",
    location: munjiCampusLocation,
    openingHours: munjiBreakfastLunchDinner,
  },
  {
    key: "hwaam-cafeteria",
    name: "화암 기숙사 식당",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 화암 기숙사 식당.",
    location: hwaamDormitoryLocation,
    openingHours: hwaamBreakfastLunchDinner,
  },
  {
    key: "seoul-campus-cafeteria",
    name: "서울캠퍼스 구내식당",
    description: "KAIST 공식 식단 페이지에서 일별 식단을 제공하는 서울캠퍼스 구내식당.",
    location: seoulCampusLocation,
    openingHours: weekdayHours([{ open: "11:30", close: "13:30" }]),
  },
  {
    key: "kaimaru-byulridalli",
    name: "별리달리",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-thekeun-siktak",
    name: "더큰식탁",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-little-hanoi",
    name: "리틀하노이",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-camto",
    name: "캠토",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-wellchai",
    name: "웰차이",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-onigiri-gyudong",
    name: "오니기리와 이규동",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-rolling-pasta",
    name: "롤링파스타",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-bearstaco",
    name: "베어스타코",
    description: "카이마루(푸드코트) 입점 매장.",
    location: kaimaruN11Location,
    openingHours: kaimaruFoodCourtHours,
  },
  {
    key: "kaimaru-juiceking",
    name: "쥬스킹",
    description: "카이마루(N11) 1층에 위치한 음료 매장.",
    location: kaimaruN11Location,
    openingHours: juiceKingHours,
  },
  {
    key: "pulbitmaru",
    name: "풀빛마루",
    description: "북측 학생회관(N12) 1층, 할랄 메뉴를 제공하는 매장.",
    location: pulbitmaruN12Location,
    openingHours: {
      monday: [{ open: "08:20", close: "18:45" }],
      tuesday: [{ open: "08:20", close: "18:45" }],
      wednesday: [{ open: "08:20", close: "18:45" }],
      thursday: [{ open: "08:20", close: "18:45" }],
      friday: [{ open: "08:20", close: "18:45" }],
      saturday: [{ open: "11:20", close: "18:30" }],
    },
  },
  {
    key: "subway",
    name: "써브웨이",
    description: "정문술빌딩(E16)에 위치한 샌드위치 매장.",
    location: chungMoonSoulE16Location,
    openingHours: {
      monday: [{ open: "08:00", close: "23:00" }],
      tuesday: [{ open: "08:00", close: "23:00" }],
      wednesday: [{ open: "08:00", close: "23:00" }],
      thursday: [{ open: "08:00", close: "23:00" }],
      friday: [{ open: "08:00", close: "23:00" }],
      saturday: [{ open: "08:00", close: "23:00" }],
      sunday: [{ open: "08:00", close: "23:00" }],
    },
  },
  {
    key: "faculty-club",
    name: "패컬티 클럽",
    description: "교직원회관(E5) 2층에 위치한 예약 중심 식당.",
    location: { ...eastFacultyClubE5Location, floor: "2F" },
    openingHours: eastFacultyLunchDinner,
  },
  {
    key: "thekeun-dosirak",
    name: "더큰도시락",
    description: "서측 학생회관(W2) 2층에 위치한 도시락 매장.",
    location: { ...westStudentCenterW2Location, floor: "2F" },
    openingHours: weekdayTenToSeven,
  },
  {
    key: "taeul-restaurant",
    name: "태울관 식당",
    description: "태울관(N13) 2층에 위치한 식당가.",
    location: taeulGwanN13Location,
    openingHours: weekdayTenThirtyToEight,
  },
];

export const KAIST_DAILY_MENU_SOURCE_SEEDS: DailyMenuSourceSeed[] = [
  {
    cafeteriaKey: "kaimaru-north-cafeteria",
    dvsCd: "fclt",
    menuNamePrefix: "카이마루",
  },
  {
    cafeteriaKey: "west-cafeteria",
    dvsCd: "west",
    menuNamePrefix: "서맛골",
  },
  {
    cafeteriaKey: "east-student-cafeteria",
    dvsCd: "east1",
    menuNamePrefix: "동맛골 학생식당",
  },
  {
    cafeteriaKey: "east-faculty-cafeteria",
    dvsCd: "east2",
    menuNamePrefix: "동맛골 교직원식당",
  },
  {
    cafeteriaKey: "faculty-hall-cafeteria",
    dvsCd: "emp",
    menuNamePrefix: "교수회관",
  },
  {
    cafeteriaKey: "munji-cafeteria",
    dvsCd: "icc",
    menuNamePrefix: "문지캠퍼스",
  },
  {
    cafeteriaKey: "hwaam-cafeteria",
    dvsCd: "hawam",
    menuNamePrefix: "화암 기숙사",
  },
  {
    cafeteriaKey: "seoul-campus-cafeteria",
    dvsCd: "seoul",
    menuNamePrefix: "서울캠퍼스",
  },
];

type FixedMenuSeedInput = Omit<
  MenuItemSeed,
  "source" | "mealTime" | "ingredients" | "allergens" | "dietaryLabels"
> &
  Partial<Pick<MenuItemSeed, "mealTime" | "ingredients" | "allergens" | "dietaryLabels">>;

const fixedMenuItem = (seed: FixedMenuSeedInput): MenuItemSeed => ({
  source: MenuSource.FIXED_MENU,
  mealTime: MealTime.ALL_DAY,
  ingredients: [],
  allergens: [],
  dietaryLabels: [],
  ...seed,
});

export const KAIST_MENU_ITEM_SEEDS: MenuItemSeed[] = [
  {
    key: "north-korean-set",
    cafeteriaKey: "kaimaru-north-cafeteria",
    source: MenuSource.DAILY_MENU,
    name: "오늘의 한식 백반",
    description: "카이마루 북측 카페테리아의 일별 학식 메뉴 예시.",
    category: CategoryCode.KOREAN,
    price: 5500,
    mealTime: MealTime.LUNCH,
    ingredients: ["rice", "soup", "kimchi", "seasonal side dishes"],
    allergens: ["SOYBEAN"],
    dietaryLabels: [],
  },
  fixedMenuItem({
    key: "byulridalli-butter-albap",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "별리달리 버터알밥",
    description: "카이마루 푸드코트 별리달리의 알밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 5000,
    ingredients: ["rice", "fish roe", "butter", "egg"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "byulridalli-flying-fish-roe-albap",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "날치알 플러스 알밥",
    description: "카이마루 푸드코트 별리달리의 날치알 알밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 5900,
    ingredients: ["rice", "flying fish roe", "vegetables"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "byulridalli-cheese-albap",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "치즈 플러스 알밥",
    description: "카이마루 푸드코트 별리달리의 치즈 알밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 6000,
    ingredients: ["rice", "fish roe", "cheese", "vegetables"],
    allergens: ["EGG", "MILK", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "byulridalli-pork-bulgogi-albap",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "돼지불고기 플러스 알밥",
    description: "카이마루 푸드코트 별리달리의 돼지불고기 알밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 6000,
    ingredients: ["rice", "fish roe", "pork bulgogi"],
    allergens: ["PORK", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "byulridalli-jeyuk-albap",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "제육 플러스 알밥",
    description: "카이마루 푸드코트 별리달리의 제육 알밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 6500,
    ingredients: ["rice", "fish roe", "spicy pork"],
    allergens: ["PORK", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "byulridalli-brisket-kimchi-stew",
    cafeteriaKey: "kaimaru-byulridalli",
    name: "차돌김치찌개와 밥",
    description: "카이마루 푸드코트 별리달리의 찌개 메뉴.",
    category: CategoryCode.KOREAN,
    price: 6400,
    ingredients: ["rice", "kimchi", "beef brisket"],
    allergens: ["BEEF", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-gimbap",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "더큰김밥",
    description: "카이마루 푸드코트 더큰식탁의 김밥 메뉴.",
    category: CategoryCode.SNACK,
    price: 2500,
    ingredients: ["rice", "seaweed", "vegetables"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-cheese-gimbap",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "치즈김밥",
    description: "카이마루 푸드코트 더큰식탁의 치즈김밥.",
    category: CategoryCode.SNACK,
    price: 3500,
    ingredients: ["rice", "seaweed", "cheese", "vegetables"],
    allergens: ["EGG", "MILK", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-egg-gimbap",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "계란김밥",
    description: "카이마루 푸드코트 더큰식탁의 계란김밥.",
    category: CategoryCode.SNACK,
    price: 3500,
    ingredients: ["rice", "seaweed", "egg", "vegetables"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-tteokbokki",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "떡볶이",
    description: "카이마루 푸드코트 더큰식탁의 분식 메뉴.",
    category: CategoryCode.SNACK,
    price: 3500,
    ingredients: ["rice cake", "gochujang", "fish cake"],
    allergens: ["SOYBEAN", "WHEAT"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-ramyeon",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "더큰라면",
    description: "카이마루 푸드코트 더큰식탁의 라면 메뉴.",
    category: CategoryCode.SNACK,
    price: 3000,
    ingredients: ["noodles", "soup"],
    allergens: ["WHEAT", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-king-pork-cutlet",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "왕돈까스",
    description: "카이마루 푸드코트 더큰식탁의 돈까스 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7000,
    ingredients: ["pork", "bread crumbs", "rice"],
    allergens: ["PORK", "WHEAT", "EGG"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "thekeun-green-onion-pork-cutlet",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "파송송돈까스",
    description: "카이마루 푸드코트 더큰식탁의 파채 돈까스 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 8000,
    ingredients: ["pork", "green onion", "bread crumbs"],
    allergens: ["PORK", "WHEAT", "EGG"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "thekeun-jeyuk-rice",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "제육덮밥",
    description: "카이마루 푸드코트 더큰식탁의 덮밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 7000,
    ingredients: ["rice", "spicy pork"],
    allergens: ["PORK", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "thekeun-tuna-kimchi-rice",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "참치김치덮밥",
    description: "카이마루 푸드코트 더큰식탁의 덮밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 6000,
    ingredients: ["rice", "tuna", "kimchi"],
    allergens: ["SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-chicken-curry-rice",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "치킨카레덮밥",
    description: "카이마루 푸드코트 더큰식탁의 카레 덮밥 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 6000,
    ingredients: ["rice", "chicken", "curry"],
    allergens: ["CHICKEN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-shrimp-curry-rice",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "새우카레덮밥",
    description: "카이마루 푸드코트 더큰식탁의 카레 덮밥 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7000,
    ingredients: ["rice", "shrimp", "curry"],
    allergens: ["SHRIMP", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-mazesoba",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "마제소바",
    description: "카이마루 푸드코트 더큰식탁의 면 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7500,
    ingredients: ["noodles", "minced meat", "egg"],
    allergens: ["WHEAT", "EGG", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-perilla-soba",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "들기름소바",
    description: "카이마루 푸드코트 더큰식탁의 면 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7000,
    ingredients: ["buckwheat noodles", "perilla oil"],
    allergens: ["BUCKWHEAT", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-fishcake-udon",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "꼬치어묵우동",
    description: "카이마루 푸드코트 더큰식탁의 우동 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 5500,
    ingredients: ["udon noodles", "fish cake", "soup"],
    allergens: ["WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "thekeun-shrimp-tempura-udon",
    cafeteriaKey: "kaimaru-thekeun-siktak",
    name: "새우튀김우동",
    description: "카이마루 푸드코트 더큰식탁의 우동 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 6000,
    ingredients: ["udon noodles", "shrimp tempura", "soup"],
    allergens: ["SHRIMP", "WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "little-hanoi-basic-pho",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "기본 쌀국수",
    description: "카이마루 푸드코트 리틀하노이의 쌀국수 메뉴.",
    category: CategoryCode.ASIAN,
    price: 4500,
    ingredients: ["rice noodles", "broth", "herbs"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "little-hanoi-brisket-pho",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "양지 쌀국수",
    description: "카이마루 푸드코트 리틀하노이의 쌀국수 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6000,
    ingredients: ["rice noodles", "beef brisket", "herbs"],
    allergens: ["BEEF"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "little-hanoi-spicy-brisket-pho",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "매운 양지 쌀국수",
    description: "카이마루 푸드코트 리틀하노이의 매운 쌀국수 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6500,
    ingredients: ["rice noodles", "beef brisket", "spicy broth"],
    allergens: ["BEEF"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "little-hanoi-fried-noodles",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "하노이 볶음면",
    description: "카이마루 푸드코트 리틀하노이의 볶음면 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6500,
    ingredients: ["noodles", "vegetables", "soy sauce"],
    allergens: ["WHEAT", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "little-hanoi-pineapple-fried-rice",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "파인애플 볶음밥",
    description: "카이마루 푸드코트 리틀하노이의 볶음밥 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6500,
    ingredients: ["rice", "pineapple", "vegetables"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "little-hanoi-cha-gio",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "짜조",
    description: "카이마루 푸드코트 리틀하노이의 사이드 메뉴.",
    category: CategoryCode.SNACK,
    price: 5400,
    ingredients: ["rice paper", "vegetables", "meat"],
    allergens: ["SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "little-hanoi-cream-onion-chicken",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "크림양파 통살치킨",
    description: "카이마루 푸드코트 리틀하노이의 치킨 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6400,
    ingredients: ["chicken", "cream sauce", "onion"],
    allergens: ["CHICKEN", "MILK", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "little-hanoi-bun-cha",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "하노이 분짜",
    description: "카이마루 푸드코트 리틀하노이의 분짜 메뉴.",
    category: CategoryCode.ASIAN,
    price: 9400,
    ingredients: ["rice noodles", "meat", "vegetables"],
    allergens: ["SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "little-hanoi-tom-yum-pho",
    cafeteriaKey: "kaimaru-little-hanoi",
    name: "똠얌 쌀국수",
    description: "카이마루 푸드코트 리틀하노이의 똠얌 쌀국수 메뉴.",
    category: CategoryCode.ASIAN,
    price: 9000,
    ingredients: ["rice noodles", "tom yum soup", "shrimp"],
    allergens: ["SHRIMP"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "wellchai-jajangmyeon",
    cafeteriaKey: "kaimaru-wellchai",
    name: "웰차이 짜장면",
    description: "카이마루 푸드코트 웰차이의 중식 메뉴.",
    category: CategoryCode.CHINESE,
    price: 5500,
    ingredients: ["wheat noodles", "black bean sauce", "onion"],
    allergens: ["WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "wellchai-jjamppong",
    cafeteriaKey: "kaimaru-wellchai",
    name: "짬뽕",
    description: "카이마루 푸드코트 웰차이의 중식 메뉴.",
    category: CategoryCode.CHINESE,
    price: 6500,
    ingredients: ["wheat noodles", "seafood", "spicy soup"],
    allergens: ["WHEAT", "SHRIMP", "SQUID", "SHELLFISH"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "wellchai-fried-rice",
    cafeteriaKey: "kaimaru-wellchai",
    name: "볶음밥",
    description: "카이마루 푸드코트 웰차이의 중식 메뉴.",
    category: CategoryCode.CHINESE,
    price: 6500,
    ingredients: ["rice", "egg", "vegetables"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "wellchai-tang-jajang",
    cafeteriaKey: "kaimaru-wellchai",
    name: "탕짜면",
    description: "카이마루 푸드코트 웰차이의 반반 중식 메뉴.",
    category: CategoryCode.CHINESE,
    price: 7500,
    ingredients: ["sweet and sour pork", "black bean noodles"],
    allergens: ["PORK", "WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "wellchai-tang-jjamppong",
    cafeteriaKey: "kaimaru-wellchai",
    name: "탕짬면",
    description: "카이마루 푸드코트 웰차이의 반반 중식 메뉴.",
    category: CategoryCode.CHINESE,
    price: 7500,
    ingredients: ["sweet and sour pork", "spicy seafood noodles"],
    allergens: ["PORK", "WHEAT", "SHRIMP", "SQUID"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "wellchai-mini-tangsuyuk",
    cafeteriaKey: "kaimaru-wellchai",
    name: "미니탕수육",
    description: "카이마루 푸드코트 웰차이의 사이드 메뉴.",
    category: CategoryCode.CHINESE,
    price: 6000,
    ingredients: ["pork", "starch", "sweet and sour sauce"],
    allergens: ["PORK", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "onigiri-gyudong",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "규동",
    description: "오니기리와 이규동의 덮밥 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 6500,
    ingredients: ["rice", "beef", "onion", "soy sauce"],
    allergens: ["BEEF", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "onigiri-katsudon",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "가츠동",
    description: "오니기리와 이규동의 덮밥 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7500,
    ingredients: ["rice", "pork cutlet", "egg", "sauce"],
    allergens: ["PORK", "WHEAT", "EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "onigiri-chicken-teriyaki-don",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "치킨데리야끼동",
    description: "오니기리와 이규동의 덮밥 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 7000,
    ingredients: ["rice", "chicken", "teriyaki sauce"],
    allergens: ["CHICKEN", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "onigiri-sanuki-udon",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "사누끼우동",
    description: "오니기리와 이규동의 우동 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 5500,
    ingredients: ["udon noodles", "soup"],
    allergens: ["WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "onigiri-cold-soba",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "냉모밀",
    description: "오니기리와 이규동의 냉모밀 메뉴.",
    category: CategoryCode.JAPANESE,
    price: 6500,
    ingredients: ["buckwheat noodles", "sauce"],
    allergens: ["BUCKWHEAT", "WHEAT", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "onigiri-tuna-salad",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "참치샐러드 오니기리",
    description: "오니기리와 이규동의 오니기리 메뉴.",
    category: CategoryCode.SNACK,
    price: 2500,
    ingredients: ["rice", "seaweed", "tuna", "mayonnaise"],
    allergens: ["EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "onigiri-bulgogi",
    cafeteriaKey: "kaimaru-onigiri-gyudong",
    name: "소불고기 오니기리",
    description: "오니기리와 이규동의 오니기리 메뉴.",
    category: CategoryCode.SNACK,
    price: 2800,
    ingredients: ["rice", "seaweed", "beef bulgogi"],
    allergens: ["BEEF", "SOYBEAN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-tomato",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "토마토 파스타",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 6900,
    ingredients: ["pasta", "tomato sauce", "garlic"],
    allergens: ["WHEAT", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-aglio-olio",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "알리오 올리오",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 6900,
    ingredients: ["pasta", "garlic", "olive oil"],
    allergens: ["WHEAT"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-vongole",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "봉골레",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 7900,
    ingredients: ["pasta", "clam", "garlic"],
    allergens: ["WHEAT", "SHELLFISH"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-carbonara",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "까르보나라",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 8900,
    ingredients: ["pasta", "cream", "bacon"],
    allergens: ["WHEAT", "MILK", "PORK", "EGG"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF],
  }),
  fixedMenuItem({
    key: "rolling-pasta-rose-shrimp",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "로제크림쉬림프파스타",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 8900,
    ingredients: ["pasta", "rose cream", "shrimp"],
    allergens: ["WHEAT", "MILK", "SHRIMP", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-seafood-tomato",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "해물토마토파스타",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 8900,
    ingredients: ["pasta", "seafood", "tomato sauce"],
    allergens: ["WHEAT", "TOMATO", "SHRIMP", "SQUID", "SHELLFISH"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-spicy-beef-tomato",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "매운우삼겹토마토파스타",
    description: "카이마루 푸드코트 롤링파스타의 파스타 메뉴.",
    category: CategoryCode.WESTERN,
    price: 8900,
    ingredients: ["pasta", "beef brisket", "tomato sauce"],
    allergens: ["WHEAT", "BEEF", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-margherita-pizza",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "마르게리따 피자 S",
    description: "카이마루 푸드코트 롤링파스타의 피자 메뉴.",
    category: CategoryCode.WESTERN,
    price: 6800,
    ingredients: ["pizza dough", "tomato", "cheese"],
    allergens: ["WHEAT", "MILK", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-gorgonzola-pizza",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "고르곤졸라 피자 S",
    description: "카이마루 푸드코트 롤링파스타의 피자 메뉴.",
    category: CategoryCode.WESTERN,
    price: 7300,
    ingredients: ["pizza dough", "gorgonzola", "cheese"],
    allergens: ["WHEAT", "MILK"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "rolling-pasta-green-salad",
    cafeteriaKey: "kaimaru-rolling-pasta",
    name: "그린샐러드",
    description: "카이마루 푸드코트 롤링파스타의 샐러드 메뉴.",
    category: CategoryCode.SALAD,
    price: 5000,
    ingredients: ["lettuce", "vegetables", "dressing"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "bearstaco-beef-taco",
    cafeteriaKey: "kaimaru-bearstaco",
    name: "비프타코",
    description: "카이마루 푸드코트 베어스타코의 타코 메뉴.",
    category: CategoryCode.WESTERN,
    price: 9900,
    ingredients: ["tortilla", "beef", "tomato", "lettuce"],
    allergens: ["BEEF", "WHEAT", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "bearstaco-chicken-burrito",
    cafeteriaKey: "kaimaru-bearstaco",
    name: "치킨부리또",
    description: "카이마루 푸드코트 베어스타코의 부리또 메뉴.",
    category: CategoryCode.WESTERN,
    price: 9900,
    ingredients: ["tortilla", "chicken", "rice", "vegetables"],
    allergens: ["CHICKEN", "WHEAT", "TOMATO"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "bearstaco-chicken-quesadilla",
    cafeteriaKey: "kaimaru-bearstaco",
    name: "치킨퀘사디아",
    description: "카이마루 푸드코트 베어스타코의 퀘사디아 메뉴.",
    category: CategoryCode.WESTERN,
    price: 9500,
    ingredients: ["tortilla", "chicken", "cheese"],
    allergens: ["CHICKEN", "WHEAT", "MILK"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "bearstaco-nacho-chips",
    cafeteriaKey: "kaimaru-bearstaco",
    name: "나초칩",
    description: "카이마루 푸드코트 베어스타코의 사이드 메뉴.",
    category: CategoryCode.SNACK,
    price: 3500,
    ingredients: ["corn chips", "salsa"],
    allergens: ["TOMATO"],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "bearstaco-soda",
    cafeteriaKey: "kaimaru-bearstaco",
    name: "탄산음료",
    description: "카이마루 푸드코트 베어스타코의 음료 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 2000,
    ingredients: ["soda"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "camto-ham-cheese-toast",
    cafeteriaKey: "kaimaru-camto",
    name: "햄치즈토스트",
    description: "카이마루 푸드코트 캠토의 토스트 메뉴.",
    category: CategoryCode.SNACK,
    price: 3800,
    ingredients: ["bread", "ham", "cheese"],
    allergens: ["WHEAT", "MILK", "PORK"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "camto-bacon-toast",
    cafeteriaKey: "kaimaru-camto",
    name: "베이컨토스트",
    description: "카이마루 푸드코트 캠토의 토스트 메뉴.",
    category: CategoryCode.SNACK,
    price: 4500,
    ingredients: ["bread", "bacon", "egg"],
    allergens: ["WHEAT", "PORK", "EGG"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "camto-bagel-sandwich",
    cafeteriaKey: "kaimaru-camto",
    name: "베이글샌드위치",
    description: "카이마루 푸드코트 캠토의 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 5500,
    ingredients: ["bagel", "vegetables", "cheese"],
    allergens: ["WHEAT", "MILK"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "camto-chicken-mayo-rice-bowl",
    cafeteriaKey: "kaimaru-camto",
    name: "치킨마요컵밥",
    description: "카이마루 푸드코트 캠토의 컵밥 메뉴.",
    category: CategoryCode.KOREAN,
    price: 5500,
    ingredients: ["rice", "chicken", "mayonnaise"],
    allergens: ["CHICKEN", "EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "camto-americano",
    cafeteriaKey: "kaimaru-camto",
    name: "아메리카노",
    description: "카이마루 푸드코트 캠토의 커피 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 2500,
    ingredients: ["coffee"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "camto-fresh-fruit-juice",
    cafeteriaKey: "kaimaru-camto",
    name: "생과일주스",
    description: "카이마루 푸드코트 캠토의 음료 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 4500,
    ingredients: ["fruit", "ice"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "pulbitmaru-halal-burrito",
    cafeteriaKey: "pulbitmaru",
    name: "할랄 브리또",
    description: "풀빛마루의 고정 메뉴판 항목.",
    category: CategoryCode.ASIAN,
    price: 6500,
    ingredients: ["tortilla", "chicken", "rice", "vegetables"],
    allergens: ["CHICKEN", "WHEAT"],
    dietaryLabels: [DietaryLabelCode.HALAL, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "pulbitmaru-spicy-chicken-rice",
    cafeteriaKey: "pulbitmaru",
    name: "매콤 닭고기 덮밥",
    description: "풀빛마루의 할랄 덮밥 메뉴.",
    category: CategoryCode.ASIAN,
    price: 6500,
    ingredients: ["rice", "chicken", "vegetables"],
    allergens: ["CHICKEN", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.HALAL, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "pulbitmaru-vegetarian-sandwich",
    cafeteriaKey: "pulbitmaru",
    name: "베지테리언 샌드위치",
    description: "풀빛마루의 베지테리언 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 5100,
    ingredients: ["bread", "vegetables", "cheese"],
    allergens: ["WHEAT", "MILK"],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "pulbitmaru-salad",
    cafeteriaKey: "pulbitmaru",
    name: "샐러드",
    description: "풀빛마루의 샐러드 메뉴.",
    category: CategoryCode.SALAD,
    price: 3000,
    ingredients: ["vegetables", "dressing"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "pulbitmaru-fruit-juice",
    cafeteriaKey: "pulbitmaru",
    name: "과일주스",
    description: "풀빛마루의 음료 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 4500,
    ingredients: ["fruit", "ice"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "pulbitmaru-yogurt",
    cafeteriaKey: "pulbitmaru",
    name: "요거트",
    description: "풀빛마루의 디저트 메뉴.",
    category: CategoryCode.DESSERT,
    price: 3500,
    ingredients: ["yogurt"],
    allergens: ["MILK"],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "subway-egg-mayo",
    cafeteriaKey: "subway",
    name: "에그마요",
    description: "써브웨이 KAIST 매장의 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 6200,
    ingredients: ["bread", "egg", "mayonnaise", "vegetables"],
    allergens: ["WHEAT", "EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "subway-italian-bmt",
    cafeteriaKey: "subway",
    name: "이탈리안 비엠티",
    description: "써브웨이 KAIST 매장의 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 7500,
    ingredients: ["bread", "salami", "pepperoni", "ham", "vegetables"],
    allergens: ["WHEAT", "PORK"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "subway-chicken-teriyaki",
    cafeteriaKey: "subway",
    name: "치킨 데리야끼",
    description: "써브웨이 KAIST 매장의 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 7800,
    ingredients: ["bread", "chicken", "teriyaki sauce", "vegetables"],
    allergens: ["WHEAT", "CHICKEN", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "subway-tuna",
    cafeteriaKey: "subway",
    name: "참치",
    description: "써브웨이 KAIST 매장의 샌드위치 메뉴.",
    category: CategoryCode.WESTERN,
    price: 6900,
    ingredients: ["bread", "tuna", "mayonnaise", "vegetables"],
    allergens: ["WHEAT", "EGG", "SOYBEAN"],
    dietaryLabels: [DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "subway-cookie",
    cafeteriaKey: "subway",
    name: "쿠키",
    description: "써브웨이 KAIST 매장의 디저트 메뉴.",
    category: CategoryCode.DESSERT,
    price: 1300,
    ingredients: ["wheat", "sugar", "butter"],
    allergens: ["WHEAT", "MILK", "EGG"],
    dietaryLabels: [DietaryLabelCode.VEGETARIAN, DietaryLabelCode.NO_BEEF, DietaryLabelCode.NO_PORK],
  }),
  fixedMenuItem({
    key: "juiceking-fruit-juice",
    cafeteriaKey: "kaimaru-juiceking",
    name: "쥬스킹 생과일주스",
    description: "카이마루 쥬스킹의 생과일주스 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 4500,
    ingredients: ["fruit", "ice"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "juiceking-strawberry-banana",
    cafeteriaKey: "kaimaru-juiceking",
    name: "딸기바나나주스",
    description: "카이마루 쥬스킹의 생과일주스 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 4500,
    ingredients: ["strawberry", "banana", "ice"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "juiceking-kiwi-juice",
    cafeteriaKey: "kaimaru-juiceking",
    name: "키위주스",
    description: "카이마루 쥬스킹의 생과일주스 메뉴.",
    category: CategoryCode.BEVERAGE,
    price: 4500,
    ingredients: ["kiwi", "ice"],
    allergens: [],
    dietaryLabels: [DietaryLabelCode.VEGAN, DietaryLabelCode.VEGETARIAN],
  }),
  fixedMenuItem({
    key: "faculty-club-set",
    cafeteriaKey: "faculty-club",
    name: "패컬티 클럽 점심 정식",
    description: "패컬티 클럽의 점심 정식 메뉴.",
    category: CategoryCode.KOREAN,
    price: 9000,
    mealTime: MealTime.LUNCH,
    ingredients: ["rice", "soup", "seasonal side dishes"],
    allergens: ["SOYBEAN"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "thekeun-dosirak-set",
    cafeteriaKey: "thekeun-dosirak",
    name: "더큰도시락 정식",
    description: "더큰도시락의 고정 메뉴판 항목.",
    category: CategoryCode.KOREAN,
    price: 8000,
    mealTime: MealTime.LUNCH,
    ingredients: ["rice", "main dish", "side dishes"],
    allergens: ["SOYBEAN", "WHEAT"],
    dietaryLabels: [],
  }),
  fixedMenuItem({
    key: "taeul-seolleongtang",
    cafeteriaKey: "taeul-restaurant",
    name: "태울관 설렁탕",
    description: "태울관 식당가의 고정 메뉴판 항목.",
    category: CategoryCode.KOREAN,
    price: 9000,
    mealTime: MealTime.LUNCH,
    ingredients: ["beef broth", "rice", "green onion"],
    allergens: ["BEEF"],
    dietaryLabels: [DietaryLabelCode.NO_PORK],
  }),
];
